---
abstract: 'Perl JSON Web Encryption (JWE) implementation'
author:
  - 'Companies House <chgovuk@cpan.org>'
build_requires:
  Crypt::Rijndael: '0'
  Module::Build: '0.3601'
  Test::Requires: '0'
configure_requires:
  Module::Build: '0.3601'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.019, CPAN::Meta::Converter version 2.141520'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: JSON-WebEncryption
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
requires:
  Crypt::CBC: '0'
  Crypt::OpenSSL::RSA: '0'
  JSON: '0'
resources:
  bugtracker: https://github.com/companieshouse/JSON-WebEncryption/issues
  homepage: https://github.com/companieshouse/JSON-WebEncryption
  repository: https://github.com/companieshouse/JSON-WebEncryption.git
version: '0.05'
